"""Single end-to-end test documenting how each memory tier
populates through the chat route's `_write_memory_turns` path.

Acts as the canonical reference test: future maintainers can read this
ONE file to understand which tier the chat route writes directly, which
tier the summarizer writes, which tier is read-only (a window over
another tier), and which API populates each.

The four memory tiers (per `modelmeld.memory.tiers`):

  - L0 raw log: every user/assistant turn, complete. Written by the
    chat route on every successful completion (`_write_memory_turns`).
    This file verifies: a single chat request lands exactly one user
    turn + one assistant turn in L0.

  - L1 facts: persistent key/value carry-forward state about the
    session. NOT auto-populated by the chat route — facts are either
    set explicitly via `store.set_fact()` or extracted by a separate
    summarizer worker. This file verifies: chat-route activity alone
    does NOT create L1 facts (so any L1 content reflects deliberate
    summarizer/API decisions, not silent inference).

  - L2 summary: evolving long-context summary, regenerated by the
    summarizer worker. NOT auto-populated by the chat route. This
    file verifies the same negative invariant.

  - L3 hot zone: recent verbatim turns ready to replay in FULL mode.
    Conceptually a window over L0, not a separately-written store.
    This file verifies: the L3 replay window reflects the last N turns
    of L0 as written by the chat route.

The hand-written tier-by-tier tests in `test_memory_in_memory.py`,
`test_chat_memory_integration.py`, and `test_chat_memory_injection.py`
cover each tier in depth. This file pulls them into one narrative for
documentation + regression-safety.
"""

from __future__ import annotations

from collections.abc import AsyncIterator

import httpx

from modelmeld.adapters.base import ProviderAdapter
from modelmeld.api.schemas import (
    ChatCompletion,
    ChatCompletionChunk,
    ChatCompletionRequest,
    Choice,
    ResponseMessage,
    Usage,
)
from modelmeld.api.server import build_app
from modelmeld.memory import (
    ANONYMOUS_TENANT_ID,
    HEADER_MEMORY_MODE,
    HEADER_SESSION_ID,
    InMemoryMemoryStore,
    Role,
)


class _MarkerAdapter(ProviderAdapter):
    """Adapter that returns a deterministic marker so we can assert which
    assistant content landed in L0."""

    name = "marker"
    is_egress = False

    def __init__(self) -> None:
        self.requests: list[ChatCompletionRequest] = []

    async def chat(self, request: ChatCompletionRequest) -> ChatCompletion:
        self.requests.append(request.model_copy(deep=True))
        # Echo the user message so we can identify which turn this response
        # corresponds to when reading L0 back.
        last_user = ""
        for m in reversed(request.messages):
            if m.role == "user" and isinstance(m.content, str):
                last_user = m.content
                break
        return ChatCompletion(
            model=request.model,
            choices=[Choice(
                index=0,
                message=ResponseMessage(content=f"reply-to: {last_user}"),
                finish_reason="stop",
            )],
            usage=Usage(prompt_tokens=1, completion_tokens=1, total_tokens=2),
        )

    async def stream_chat(
        self, request: ChatCompletionRequest,
    ) -> AsyncIterator[ChatCompletionChunk]:
        if False:  # pragma: no cover
            yield

    async def health(self) -> bool:
        return True


def _payload(text: str) -> dict:
    return {"model": "stub", "messages": [{"role": "user", "content": text}]}


async def test_chat_route_writes_l0_only_l1_l2_unchanged() -> None:
    """Three chat requests through the route. Verify:
      * L0 (turns): 6 entries — 3 user + 3 assistant, in order
      * L1 (facts): unchanged from initial empty (chat route doesn't
        infer facts; that's the summarizer's job)
      * L2 (summary): unchanged from initial empty (same)
      * L3 (replay window in FULL mode): exposes turns 1-2 to turn 3
    """
    store = InMemoryMemoryStore()
    adapter = _MarkerAdapter()
    app = build_app(adapter=adapter, memory_store=store)

    sess = "tier-test-1"
    headers = {HEADER_SESSION_ID: sess, HEADER_MEMORY_MODE: "full"}

    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app), base_url="http://test",
    ) as client:
        await client.post(
            "/v1/chat/completions", json=_payload("hello"), headers=headers,
        )
        await client.post(
            "/v1/chat/completions", json=_payload("how are you"), headers=headers,
        )
        await client.post(
            "/v1/chat/completions", json=_payload("goodbye"), headers=headers,
        )

    # ---- L0 raw log ----
    # 3 user turns + 3 assistant turns = 6 total, append order preserved.
    l0_turns = await store.list_turns(sess, ANONYMOUS_TENANT_ID)
    assert len(l0_turns) == 6, (
        f"L0 should hold 3 user + 3 assistant turns; got {len(l0_turns)}"
    )
    roles_in_order = [t.role for t in l0_turns]
    assert roles_in_order == [
        Role.USER, Role.ASSISTANT,
        Role.USER, Role.ASSISTANT,
        Role.USER, Role.ASSISTANT,
    ]
    contents_in_order = [t.content for t in l0_turns]
    assert contents_in_order == [
        "hello", "reply-to: hello",
        "how are you", "reply-to: how are you",
        "goodbye", "reply-to: goodbye",
    ]

    # ---- L1 facts ----
    # The chat route MUST NOT infer facts from turns. That's the summarizer
    # worker's job, and the summarizer was not invoked here.
    facts = await store.get_facts(sess, ANONYMOUS_TENANT_ID)
    assert facts == [], (
        f"chat route silently created L1 facts: {facts!r} — this would be a "
        "boundary violation: only the summarizer worker writes L1."
    )

    # ---- L2 summary ----
    # Same invariant. No summary unless the summarizer ran.
    summary = await store.get_summary(sess, ANONYMOUS_TENANT_ID)
    assert summary is None, (
        f"chat route silently created an L2 summary: {summary!r}"
    )

    # ---- L3 hot zone (via the request hitting turn 3) ----
    # In FULL mode, turn 3's adapter saw turns 1 + 2 replayed as L3
    # before its own current-turn user message. Inspect what landed.
    turn3_req = adapter.requests[2]
    all_text = []
    for m in turn3_req.messages:
        if isinstance(m.content, str):
            all_text.append(m.content)
    blob = "\n".join(all_text)
    # Prior user messages were "hello" and "how are you"; both should
    # appear as L3 replay before turn 3's own "goodbye".
    assert "hello" in blob, f"L3 replay missing 'hello':\n{blob!r}"
    assert "how are you" in blob, f"L3 replay missing 'how are you':\n{blob!r}"
    assert "goodbye" in blob


async def test_explicitly_set_facts_are_returned_through_store_api() -> None:
    """Counter-test to the negative invariant above: when the summarizer
    (or any caller) DOES populate L1 via the public API, the chat route
    properly reads + injects those facts on subsequent requests.

    Complements `test_facts_injected_into_subsequent_request` in
    `test_chat_memory_injection.py` by being explicit about WHERE the
    fact came from — the public store API, not the chat route itself."""
    store = InMemoryMemoryStore()
    adapter = _MarkerAdapter()
    app = build_app(adapter=adapter, memory_store=store)

    sess = "tier-test-2"

    # Caller explicitly writes a fact via the public store API.
    # (In production this would be the summarizer worker writing
    #  extracted facts; here we simulate that with a direct write.)
    await store.get_or_create_session(sess, ANONYMOUS_TENANT_ID)
    await store.set_fact(sess, ANONYMOUS_TENANT_ID, "user_name", "Alice")

    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app), base_url="http://test",
    ) as client:
        await client.post(
            "/v1/chat/completions", json=_payload("turn 1"),
            headers={HEADER_SESSION_ID: sess},
        )

    # The chat route read the fact from L1 and injected it as a system
    # message into the adapter call.
    assert len(adapter.requests) == 1
    req = adapter.requests[0]
    sys_msgs = [m for m in req.messages if m.role == "system"]
    sys_blob = "\n".join(
        m.content for m in sys_msgs if isinstance(m.content, str)
    )
    assert "user_name: Alice" in sys_blob, (
        f"fact set via store API didn't reach the adapter:\n{sys_blob!r}"
    )

    # And the chat route's L0 write still happened — 2 new turns landed
    # alongside the read.
    l0_turns = await store.list_turns(sess, ANONYMOUS_TENANT_ID)
    assert len(l0_turns) == 2
    assert l0_turns[0].content == "turn 1"
    assert l0_turns[1].content == "reply-to: turn 1"
